import { NextRequest, NextResponse } from "next/server";
import { createServer } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
  const supabase = await createServer();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // First, get all models accessible to user (RLS will handle access control)
    const { data: userModels } = await supabase
      .from("models")
      .select("id");

    const modelIds = userModels?.map(m => m.id) || [];

    // Get variant row IDs owned by the user for variant image counting
    const { data: userVariantRows } = await supabase
      .from("variant_rows")
      .select("id")
      .eq("user_id", user.id);

    const variantRowIds = userVariantRows?.map(r => r.id) || [];

    // Fetch all statistics in parallel
    const [
      modelsCount,
      imagesCount,
      variantImagesCount,
      rowsCount,
      jobsCount,
      activeJobsCount,
    ] = await Promise.all([
      // Total models accessible to user (RLS handles access)
      supabase
        .from("models")
        .select("id", { count: "exact", head: true }),
      
      // Total images generated by user (only count images where user_id matches)
      supabase
        .from("generated_images")
        .select("id", { count: "exact", head: true })
        .eq("user_id", user.id),
      
      // Total variant-generated images for user's variant rows only
      variantRowIds.length > 0
        ? supabase
            .from("variant_row_images")
            .select("id", { count: "exact", head: true })
            .eq("is_generated", true)
            .in("variant_row_id", variantRowIds)
        : Promise.resolve({ count: 0, error: null }),
      
      // Total rows across all user's accessible models
      modelIds.length > 0
        ? supabase
            .from("model_rows")
            .select("id", { count: "exact", head: true })
            .in("model_id", modelIds)
        : Promise.resolve({ count: 0, error: null }),
      
      // Total jobs created by user
      supabase
        .from("jobs")
        .select("id", { count: "exact", head: true })
        .eq("user_id", user.id),
      
      // Active jobs (queued, submitted, running, saving)
      supabase
        .from("jobs")
        .select("id", { count: "exact", head: true })
        .eq("user_id", user.id)
        .in("status", ["queued", "submitted", "running", "saving"]),
    ]);

    // Sum both image counts for total
    const totalImages = (imagesCount.count || 0) + (variantImagesCount.count || 0);

    return NextResponse.json({
      totalModels: modelsCount.count || 0,
      totalImages,
      totalRows: rowsCount.count || 0,
      totalJobs: jobsCount.count || 0,
      activeJobs: activeJobsCount.count || 0,
    });
  } catch (error) {
    console.error("[User Stats] Error:", error);
    return NextResponse.json(
      { error: "Failed to fetch statistics" },
      { status: 500 }
    );
  }
}

