export interface VariantImage {
  id: string
  outputPath: string
  thumbnailPath: string | null
  sourceRowId?: string
}

export interface VariantRowImage {
  id: string
  variant_row_id: string
  output_path: string
  thumbnail_path: string | null
  source_row_id: string | null
  position: number
  /**
   * Explicitly marks whether this image was generated by a job (result) or is a reference/source image.
   * - true: Generated image (appears in Results column)
   * - false/null/undefined: Reference image (appears in Reference column)
   * 
   * IMPORTANT: This flag must be explicitly set to true for generated images.
   * Default behavior treats null/undefined as false (reference image).
   */
  is_generated?: boolean
  is_favorited?: boolean
  created_at: string
}

/**
 * Type guard to check if an image is a generated result
 */
export function isGeneratedImage(image: VariantRowImage): boolean {
  return image.is_generated === true
}

/**
 * Type guard to check if an image is a reference image
 */
export function isReferenceImage(image: VariantRowImage): boolean {
  return image.is_generated !== true
}

/**
 * Validates and normalizes the is_generated flag
 * Ensures it's always a boolean (never null/undefined)
 */
export function normalizeIsGenerated(value: boolean | null | undefined): boolean {
  return value === true
}

export interface VariantRow {
  id: string
  user_id: string
  team_id: string
  name: string | null
  prompt: string | null
  output_width?: number
  output_height?: number
  match_target_ratio?: boolean
  created_at: string
  updated_at: string
  variant_row_images?: VariantRowImage[]
}

export interface VariantPromptGenerateRequest {
  imagePaths: string[]
}

export interface VariantPromptGenerateResponse {
  prompt: string
}

export interface VariantPromptEnhanceRequest {
  existingPrompt: string
  userInstructions: string
  imagePaths: string[]
}

export interface VariantPromptEnhanceResponse {
  prompt: string
}

export interface BatchAddImagesRequest {
  images: Array<{
    outputPath: string
    thumbnailPath?: string | null
    sourceRowId?: string | null
  }>
}

export interface BatchAddImagesResponse {
  rowsCreated: number
  imagesAdded: number
  rows: Array<{
    id: string
    imageCount: number
    sourceRowId: string | null
  }>
}

