-- Add is_generated column to variant_row_images to distinguish reference images from generated results
-- Generated images will have is_generated = true
-- Reference/source images will have is_generated = false (default)

ALTER TABLE variant_row_images 
  ADD COLUMN IF NOT EXISTS is_generated BOOLEAN NOT NULL DEFAULT false;

-- Create index for efficient filtering
CREATE INDEX IF NOT EXISTS idx_variant_row_images_is_generated 
  ON variant_row_images(variant_row_id, is_generated);

-- Add helpful comment
COMMENT ON COLUMN variant_row_images.is_generated IS 
  'True if this image was generated by a job (result), false if it is a reference/source image';

